import { RatingCriterionId } from "./types"

export type RatingCriterion = {
  id: RatingCriterionId
  group: "taste" | "aroma"
  label: string
  description: string
  low: string
  mid: string
  high: string
  min: number
  max: number
  step: number
  order: number
  enabled: boolean
}

// 評価基準バージョン。基準を変更する場合は新バージョンを追加し、
// 過去評価データが参照するバージョンの意味を変えないこと（README §14）。
export const RATING_CRITERIA_VERSION = "v1"

export const RATING_CRITERIA: RatingCriterion[] = [
  // 味覚評価（7次元）
  {
    id: "sweetness",
    group: "taste",
    label: "甘み",
    description: "ワインに感じる甘さの強度",
    low: "完全辛口",
    mid: "中程度",
    high: "極甘口",
    min: 0,
    max: 10,
    step: 1,
    order: 1,
    enabled: true,
  },
  {
    id: "acidity",
    group: "taste",
    label: "酸味",
    description: "ワインの酸の強度",
    low: "非常に低い",
    mid: "中程度",
    high: "非常に高い",
    min: 0,
    max: 10,
    step: 1,
    order: 2,
    enabled: true,
  },
  {
    id: "bitterness",
    group: "taste",
    label: "苦み",
    description: "ワインに感じる苦さの強度",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 3,
    enabled: true,
  },
  {
    id: "saltiness",
    group: "taste",
    label: "塩味",
    description: "ワインに感じる塩気の強度",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 4,
    enabled: true,
  },
  {
    id: "tannin",
    group: "taste",
    label: "タンニン",
    description: "タンニンの強度",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 5,
    enabled: true,
  },
  {
    id: "astringency",
    group: "taste",
    label: "渋み",
    description: "口の中に感じる収斂性・渋みの強度",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 6,
    enabled: true,
  },
  {
    id: "alcohol",
    group: "taste",
    label: "アルコール感",
    description: "アルコールの存在感",
    low: "軽い",
    mid: "中程度",
    high: "強い",
    min: 0,
    max: 10,
    step: 1,
    order: 7,
    enabled: true,
  },
  // 香り評価（15次元）
  {
    id: "aromaIntensity",
    group: "aroma",
    label: "香りの強さ",
    description: "香り全体の強度",
    low: "非常に弱い",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 8,
    enabled: true,
  },
  {
    id: "citrus",
    group: "aroma",
    label: "柑橘系",
    description: "レモン、グレープフルーツ等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 9,
    enabled: true,
  },
  {
    id: "stoneFruit",
    group: "aroma",
    label: "核果系",
    description: "桃、杏等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 10,
    enabled: true,
  },
  {
    id: "tropical",
    group: "aroma",
    label: "トロピカル系",
    description: "マンゴー、パイン等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 11,
    enabled: true,
  },
  {
    id: "redFruit",
    group: "aroma",
    label: "赤果実系",
    description: "いちご、チェリー等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 12,
    enabled: true,
  },
  {
    id: "blackFruit",
    group: "aroma",
    label: "黒果実系",
    description: "カシス、ブラックベリー等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 13,
    enabled: true,
  },
  {
    id: "floral",
    group: "aroma",
    label: "フローラル",
    description: "花、バラ、スミレ等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 15,
    enabled: true,
  },
  {
    id: "herbal",
    group: "aroma",
    label: "ハーブ・青さ",
    description: "ミント、タイム、青草、ピーマン等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 16,
    enabled: true,
  },
  {
    id: "spice",
    group: "aroma",
    label: "スパイス",
    description: "胡椒、クローブ等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 17,
    enabled: true,
  },
  {
    id: "nutty",
    group: "aroma",
    label: "ナッツ",
    description: "アーモンド、ヘーゼルナッツ等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 18,
    enabled: true,
  },
  {
    id: "earthy",
    group: "aroma",
    label: "土・森林・動物",
    description: "土、森林、きのこ、なめし革等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 19,
    enabled: true,
  },
  {
    id: "oak",
    group: "aroma",
    label: "樽香",
    description: "バニラ、トースト等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 1,
    order: 20,
    enabled: true,
  },
]
