import { RatingCriterionId } from "./types"

export type RatingCriterion = {
  id: RatingCriterionId
  group: "taste" | "aroma"
  label: string
  description: string
  low: string
  mid: string
  high: string
  min: number
  max: number
  step: number
  order: number
  enabled: boolean
}

// 評価基準バージョン。基準を変更する場合は新バージョンを追加し、
// 過去評価データが参照するバージョンの意味を変えないこと（README §14）。
export const RATING_CRITERIA_VERSION = "v1"

export const RATING_CRITERIA: RatingCriterion[] = [
  // 味覚・構造評価（8次元）
  {
    id: "sweetness",
    group: "taste",
    label: "甘味",
    description: "ワインに感じる甘さの強度",
    low: "完全辛口",
    mid: "中程度",
    high: "極甘口",
    min: 0,
    max: 10,
    step: 0.5,
    order: 1,
    enabled: true,
  },
  {
    id: "acidity",
    group: "taste",
    label: "酸味",
    description: "ワインの酸の強度",
    low: "非常に低い",
    mid: "中程度",
    high: "非常に高い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 2,
    enabled: true,
  },
  {
    id: "tannin",
    group: "taste",
    label: "タンニン",
    description: "渋みの強度",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 3,
    enabled: true,
  },
  {
    id: "body",
    group: "taste",
    label: "ボディ",
    description: "口当たりの重さ・厚み",
    low: "ライト",
    mid: "ミディアム",
    high: "フル",
    min: 0,
    max: 10,
    step: 0.5,
    order: 4,
    enabled: true,
  },
  {
    id: "alcohol",
    group: "taste",
    label: "アルコール感",
    description: "アルコールの存在感",
    low: "軽い",
    mid: "中程度",
    high: "強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 5,
    enabled: true,
  },
  {
    id: "fruitiness",
    group: "taste",
    label: "果実味",
    description: "果実由来の風味の豊かさ",
    low: "控えめ",
    mid: "中程度",
    high: "非常に豊か",
    min: 0,
    max: 10,
    step: 0.5,
    order: 6,
    enabled: true,
  },
  {
    id: "minerality",
    group: "taste",
    label: "ミネラル感",
    description: "鉱物的な風味の強度",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 7,
    enabled: true,
  },
  {
    id: "finish",
    group: "taste",
    label: "余韻",
    description: "後味が続く長さ",
    low: "短い",
    mid: "中程度",
    high: "非常に長い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 8,
    enabled: true,
  },
  // 香り評価（15次元）
  {
    id: "aromaIntensity",
    group: "aroma",
    label: "香りの強さ",
    description: "香り全体の強度",
    low: "非常に弱い",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 9,
    enabled: true,
  },
  {
    id: "citrus",
    group: "aroma",
    label: "柑橘系",
    description: "レモン、グレープフルーツ等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 10,
    enabled: true,
  },
  {
    id: "stoneFruit",
    group: "aroma",
    label: "核果系",
    description: "桃、杏等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 11,
    enabled: true,
  },
  {
    id: "tropical",
    group: "aroma",
    label: "トロピカル系",
    description: "マンゴー、パイン等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 12,
    enabled: true,
  },
  {
    id: "redFruit",
    group: "aroma",
    label: "赤果実系",
    description: "いちご、チェリー等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 13,
    enabled: true,
  },
  {
    id: "blackFruit",
    group: "aroma",
    label: "黒果実系",
    description: "カシス、ブラックベリー等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 14,
    enabled: true,
  },
  {
    id: "driedFruit",
    group: "aroma",
    label: "ドライフルーツ系",
    description: "レーズン、プルーン等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 15,
    enabled: true,
  },
  {
    id: "floral",
    group: "aroma",
    label: "フローラル",
    description: "花、バラ、スミレ等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 16,
    enabled: true,
  },
  {
    id: "herbal",
    group: "aroma",
    label: "ハーブ",
    description: "ミント、タイム等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 17,
    enabled: true,
  },
  {
    id: "green",
    group: "aroma",
    label: "青さ",
    description: "青草、ピーマン等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 18,
    enabled: true,
  },
  {
    id: "spice",
    group: "aroma",
    label: "スパイス",
    description: "胡椒、クローブ等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 19,
    enabled: true,
  },
  {
    id: "oak",
    group: "aroma",
    label: "樽香",
    description: "バニラ、トースト等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 20,
    enabled: true,
  },
  {
    id: "nutty",
    group: "aroma",
    label: "ナッツ",
    description: "アーモンド、ヘーゼルナッツ等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 21,
    enabled: true,
  },
  {
    id: "earthy",
    group: "aroma",
    label: "土・森林",
    description: "土、森林、きのこ等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 22,
    enabled: true,
  },
  {
    id: "aged",
    group: "aroma",
    label: "熟成香",
    description: "蜂蜜、熟成由来の香り等",
    low: "感じない",
    mid: "中程度",
    high: "非常に強い",
    min: 0,
    max: 10,
    step: 0.5,
    order: 23,
    enabled: true,
  },
]
