import { WineEvaluation } from "./types"

// Claude の一般的なワイン知識に基づく、各ワインのスタイルを反映した評価例。
// 実ヴィンテージ固有の官能データではなく、デモ表示用の代表値。
export const SEED_EVALUATIONS: WineEvaluation[] = [
  {
    id: "seed-eval-chateau-margaux",
    wineName: "シャトー・マルゴー",
    producer: "Château Margaux",
    grapeVarieties: ["カベルネ・ソーヴィニョン", "メルロ"],
    country: "フランス",
    region: "ボルドー（マルゴー）",
    vintage: 2015,
    wineAlcoholPercent: 13.5,
    wineMemo: "ボルドー格付け第1級。優雅で緻密なタンニンが特徴の世界最高峰の赤ワイン。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-01T09:00:00.000Z",
    sweetness: 1,
    acidity: 6.5,
    bitterness: 2.0,
    saltiness: 4,
    tannin: 6.5,
    astringency: 6.5,
    alcohol: 6,
    aromaIntensity: 7.5,
    citrus: 1,
    stoneFruit: 1,
    tropical: 0,
    redFruit: 4,
    blackFruit: 7,
    floral: 5,
    herbal: 1.5,
    spice: 3,
    oak: 6,
    nutty: 1.5,
    earthy: 2.5,
    comment:
      "エレガントで緻密なタンニン。カシスとスミレの香り、樽由来のバニラが上品に溶け込む。余韻は非常に長い。",
  },
  {
    id: "seed-eval-romanee-conti",
    wineName: "ロマネ・コンティ",
    producer: "Domaine de la Romanée-Conti",
    grapeVarieties: ["ピノ・ノワール"],
    country: "フランス",
    region: "ブルゴーニュ（ヴォーヌ・ロマネ）",
    vintage: 2018,
    wineAlcoholPercent: 13,
    wineMemo: "世界で最も稀少とされるグラン・クリュ。芳醇な香りと複雑な余韻。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-02T09:00:00.000Z",
    sweetness: 0.5,
    acidity: 7.5,
    bitterness: 1.0,
    saltiness: 5,
    tannin: 3.5,
    astringency: 3.5,
    alcohol: 5.5,
    aromaIntensity: 8,
    citrus: 0.5,
    stoneFruit: 1,
    tropical: 0,
    redFruit: 7.5,
    blackFruit: 2,
    floral: 5.5,
    herbal: 1.0,
    spice: 3.5,
    oak: 3.5,
    nutty: 1,
    earthy: 4.5,
    comment:
      "赤いベリーとバラの華やかな香り。繊細なタンニンとシルキーな質感、複雑で長い余韻。",
  },
  {
    id: "seed-eval-dom-perignon",
    wineName: "ドン・ペリニヨン",
    producer: "Moët & Chandon",
    grapeVarieties: ["シャルドネ", "ピノ・ノワール"],
    country: "フランス",
    region: "シャンパーニュ",
    vintage: 2013,
    wineAlcoholPercent: 12.5,
    wineMemo: "ヴィンテージ・シャンパーニュの代名詞。緻密な泡と厚みのある味わい。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-03T09:00:00.000Z",
    sweetness: 1.5,
    acidity: 8,
    bitterness: 0.0,
    saltiness: 7.5,
    tannin: 0.5,
    astringency: 0.5,
    alcohol: 4.5,
    aromaIntensity: 7,
    citrus: 6.5,
    stoneFruit: 2.5,
    tropical: 1,
    redFruit: 1,
    blackFruit: 0,
    floral: 3,
    herbal: 0.5,
    spice: 1,
    oak: 2,
    nutty: 4.5,
    earthy: 1,
    comment:
      "シトラスとブリオッシュ香、緻密な泡とミネラル感。骨格のしっかりした辛口。",
  },
  {
    id: "seed-eval-opus-one",
    wineName: "オーパス・ワン",
    producer: "Opus One Winery",
    grapeVarieties: ["カベルネ・ソーヴィニョン", "メルロ"],
    country: "アメリカ",
    region: "ナパヴァレー",
    vintage: 2019,
    wineAlcoholPercent: 14.5,
    wineMemo: "ボルドーとカリフォルニアの融合から生まれたプレミアムワインの代表格。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-04T09:00:00.000Z",
    sweetness: 1,
    acidity: 5.5,
    bitterness: 2.0,
    saltiness: 2.5,
    tannin: 6.5,
    astringency: 6.5,
    alcohol: 8,
    aromaIntensity: 8,
    citrus: 0.5,
    stoneFruit: 1,
    tropical: 0,
    redFruit: 3,
    blackFruit: 8,
    floral: 2,
    herbal: 1.0,
    spice: 3.5,
    oak: 6.5,
    nutty: 1.5,
    earthy: 1.5,
    comment:
      "凝縮感のある黒果実とカカオ、樽香。滑らかなタンニンとリッチな余韻。",
  },
  {
    id: "seed-eval-sassicaia",
    wineName: "サッシカイア",
    producer: "Tenuta San Guido",
    grapeVarieties: ["カベルネ・ソーヴィニョン", "カベルネ・フラン"],
    country: "イタリア",
    region: "トスカーナ（ボルゲリ）",
    vintage: 2019,
    wineAlcoholPercent: 14,
    wineMemo: "スーパータスカンの先駆け。イタリアワインの常識を変えた一本。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-05T09:00:00.000Z",
    sweetness: 1,
    acidity: 6,
    bitterness: 2.0,
    saltiness: 3.5,
    tannin: 6,
    astringency: 6,
    alcohol: 6.5,
    aromaIntensity: 7,
    citrus: 0.5,
    stoneFruit: 1,
    tropical: 0,
    redFruit: 3.5,
    blackFruit: 6.5,
    floral: 1.5,
    herbal: 2.5,
    spice: 3,
    oak: 5,
    nutty: 1,
    earthy: 2.5,
    comment:
      "地中海ハーブを思わせる香り、カシスとタバコのニュアンス。骨格のしっかりしたミディアムボディ。",
  },
  {
    id: "seed-eval-penfolds-grange",
    wineName: "ペンフォールズ グランジ",
    producer: "Penfolds",
    grapeVarieties: ["シラーズ"],
    country: "オーストラリア",
    region: "サウスオーストラリア",
    vintage: 2018,
    wineAlcoholPercent: 14.5,
    wineMemo: "オーストラリアを代表するアイコンワイン。力強く濃厚なシラーズ。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-06T09:00:00.000Z",
    sweetness: 1,
    acidity: 5,
    bitterness: 2.0,
    saltiness: 2,
    tannin: 6.5,
    astringency: 6.5,
    alcohol: 8.5,
    aromaIntensity: 8.5,
    citrus: 0,
    stoneFruit: 0.5,
    tropical: 0,
    redFruit: 2,
    blackFruit: 8,
    floral: 1,
    herbal: 1.0,
    spice: 6,
    oak: 7,
    nutty: 1.5,
    earthy: 2,
    comment:
      "黒胡椒とブラックベリーの濃密な香り、樽由来のトースト香。力強くフルボディ。",
  },
  {
    id: "seed-eval-chateau-yquem",
    wineName: "シャトー・ディケム",
    producer: "Château d'Yquem",
    grapeVarieties: ["セミヨン", "ソーヴィニヨン・ブラン"],
    country: "フランス",
    region: "ボルドー（ソーテルヌ）",
    vintage: 2017,
    wineAlcoholPercent: 14,
    wineMemo: "貴腐ワインの最高峰。濃密な甘みと蜂蜜香、長い熟成にも耐える。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-07T09:00:00.000Z",
    sweetness: 9.5,
    acidity: 7,
    bitterness: 0.0,
    saltiness: 2,
    tannin: 0,
    astringency: 0,
    alcohol: 5.5,
    aromaIntensity: 8.5,
    citrus: 3,
    stoneFruit: 3.5,
    tropical: 2,
    redFruit: 0,
    blackFruit: 0,
    floral: 2,
    herbal: 0.0,
    spice: 1,
    oak: 3,
    nutty: 4,
    earthy: 0.5,
    comment:
      "蜂蜜とアプリコットのコンフィ、貴腐由来の複雑な甘香。高い酸が甘みを支え長い余韻へ。",
  },
  {
    id: "seed-eval-vega-sicilia-unico",
    wineName: "ベガ・シシリア ウニコ",
    producer: "Vega Sicilia",
    grapeVarieties: ["テンプラニーリョ", "カベルネ・ソーヴィニョン"],
    country: "スペイン",
    region: "リベラ・デル・ドゥエロ",
    vintage: 2011,
    wineAlcoholPercent: 14,
    wineMemo: "スペインワインの最高峰。長期熟成による複雑でエレガントな味わい。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-08T09:00:00.000Z",
    sweetness: 1,
    acidity: 5.5,
    bitterness: 1.5,
    saltiness: 2.5,
    tannin: 5.5,
    astringency: 5.5,
    alcohol: 6.5,
    aromaIntensity: 7.5,
    citrus: 0.5,
    stoneFruit: 1,
    tropical: 0,
    redFruit: 2.5,
    blackFruit: 4,
    floral: 1,
    herbal: 1.0,
    spice: 4,
    oak: 6.5,
    nutty: 3,
    earthy: 3.5,
    comment: "長期熟成由来の複雑な香り、ドライフルーツと樽、なめらかなタンニン。",
  },
  {
    id: "seed-eval-yellow-tail-shiraz",
    wineName: "イエローテイル シラーズ",
    producer: "[yellow tail]",
    grapeVarieties: ["シラーズ"],
    country: "オーストラリア",
    region: "サウス・イースタン・オーストラリア",
    vintage: 2022,
    wineAlcoholPercent: 13.5,
    wineMemo: "世界的ベストセラーの日常消費ワイン。果実味豊かで飲みやすい廉価帯の代表格。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-09T09:00:00.000Z",
    sweetness: 3,
    acidity: 4,
    bitterness: 1.0,
    saltiness: 1,
    tannin: 3.5,
    astringency: 3.5,
    alcohol: 5.5,
    aromaIntensity: 6,
    citrus: 0,
    stoneFruit: 0.5,
    tropical: 0.5,
    redFruit: 3,
    blackFruit: 6,
    floral: 1,
    herbal: 0.5,
    spice: 2,
    oak: 2,
    nutty: 0.5,
    earthy: 1,
    comment: "ジャムのような果実味と控えめなタンニン、飲みやすいカジュアルな一本。",
  },
  {
    id: "seed-eval-jacobs-creek-classic",
    wineName: "ジェイコブス・クリーク クラシック シラーズ・カベルネ",
    producer: "Jacob's Creek",
    grapeVarieties: ["シラーズ", "カベルネ・ソーヴィニョン"],
    country: "オーストラリア",
    region: "サウス・イースタン・オーストラリア",
    vintage: 2022,
    wineAlcoholPercent: 13.5,
    wineMemo: "スーパーの定番。手頃な価格帯でバランスの取れた味わい。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-10T09:00:00.000Z",
    sweetness: 2,
    acidity: 4.5,
    bitterness: 1.0,
    saltiness: 1.5,
    tannin: 4,
    astringency: 4,
    alcohol: 5.5,
    aromaIntensity: 5.5,
    citrus: 0,
    stoneFruit: 0.5,
    tropical: 0,
    redFruit: 3.5,
    blackFruit: 5,
    floral: 1,
    herbal: 1.0,
    spice: 2.5,
    oak: 2.5,
    nutty: 0.5,
    earthy: 1,
    comment: "バランスの取れた果実味とほどよいタンニン、日常使いしやすい味わい。",
  },
  {
    id: "seed-eval-cono-sur-bicicleta-pinot",
    wineName: "コノスル ビシクレタ ピノ・ノワール",
    producer: "Cono Sur",
    grapeVarieties: ["ピノ・ノワール"],
    country: "チリ",
    region: "セントラル・ヴァレー",
    vintage: 2022,
    wineAlcoholPercent: 13,
    wineMemo: "コストパフォーマンスの高さで有名なチリワイン。軽やかで果実味豊か。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-11T09:00:00.000Z",
    sweetness: 1.5,
    acidity: 6,
    bitterness: 1.0,
    saltiness: 2,
    tannin: 2.5,
    astringency: 2.5,
    alcohol: 4.5,
    aromaIntensity: 5.5,
    citrus: 0.5,
    stoneFruit: 1,
    tropical: 0,
    redFruit: 6.5,
    blackFruit: 1,
    floral: 2,
    herbal: 1.0,
    spice: 1,
    oak: 1,
    nutty: 0.5,
    earthy: 1.5,
    comment: "赤いベリーの軽やかな香りとフレッシュな酸、渋みは控えめで飲みやすい。",
  },
  {
    id: "seed-eval-carlo-rossi",
    wineName: "カルロ・ロッシ レッド",
    producer: "Carlo Rossi",
    grapeVarieties: ["ジンファンデル"],
    country: "アメリカ",
    region: "カリフォルニア",
    vintage: 2022,
    wineAlcoholPercent: 12,
    wineMemo: "アメリカの家庭向け定番デイリーワイン。軽く飲みやすい。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-12T09:00:00.000Z",
    sweetness: 3.5,
    acidity: 3.5,
    bitterness: 1.0,
    saltiness: 1,
    tannin: 2.5,
    astringency: 2.5,
    alcohol: 3.5,
    aromaIntensity: 4.5,
    citrus: 0,
    stoneFruit: 0.5,
    tropical: 0.5,
    redFruit: 4,
    blackFruit: 3,
    floral: 0.5,
    herbal: 0.5,
    spice: 1,
    oak: 0.5,
    nutty: 0.5,
    earthy: 0.5,
    comment: "軽やかで甘みのある果実味、渋みは少なくカジュアルに楽しめる。",
  },
  {
    id: "seed-eval-santa-helena-gran-reserva",
    wineName: "サンタ・ヘレナ グラン・レゼルバ カベルネ・ソーヴィニョン",
    producer: "Santa Helena",
    grapeVarieties: ["カベルネ・ソーヴィニョン"],
    country: "チリ",
    region: "コルチャグア・ヴァレー",
    vintage: 2021,
    wineAlcoholPercent: 13.5,
    wineMemo: "廉価帯でも安定した品質のチリ産カベルネ。しっかりした果実味。",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-13T09:00:00.000Z",
    sweetness: 1.5,
    acidity: 4.5,
    bitterness: 1.5,
    saltiness: 2,
    tannin: 5,
    astringency: 5,
    alcohol: 5.5,
    aromaIntensity: 6,
    citrus: 0,
    stoneFruit: 0.5,
    tropical: 0,
    redFruit: 2.5,
    blackFruit: 6,
    floral: 1,
    herbal: 1.5,
    spice: 2,
    oak: 3,
    nutty: 0.5,
    earthy: 1.5,
    comment: "しっかりした黒果実の香りとほどよいタンニン、コスパの良いカベルネ。",
  },
]
