import { WineEvaluation } from "./types"

// Claude の一般的なワイン知識に基づく、各ワインのスタイルを反映した評価例。
// 実ヴィンテージ固有の官能データではなく、デモ表示用の代表値。
export const SEED_EVALUATIONS: WineEvaluation[] = [
  {
    id: "seed-eval-chateau-margaux",
    wineId: "seed-chateau-margaux",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-01T09:00:00.000Z",
    sweetness: 1,
    acidity: 6.5,
    tannin: 6.5,
    body: 7,
    alcohol: 6,
    fruitiness: 6.5,
    minerality: 4,
    finish: 8.5,
    aromaIntensity: 7.5,
    citrus: 1,
    stoneFruit: 1,
    tropical: 0,
    redFruit: 4,
    blackFruit: 7,
    driedFruit: 2,
    floral: 5,
    herbal: 2,
    green: 1,
    spice: 3,
    oak: 6,
    nutty: 1.5,
    earthy: 2.5,
    aged: 3,
    comment:
      "エレガントで緻密なタンニン。カシスとスミレの香り、樽由来のバニラが上品に溶け込む。余韻は非常に長い。",
  },
  {
    id: "seed-eval-romanee-conti",
    wineId: "seed-romanee-conti",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-02T09:00:00.000Z",
    sweetness: 0.5,
    acidity: 7.5,
    tannin: 3.5,
    body: 4.5,
    alcohol: 5.5,
    fruitiness: 6.5,
    minerality: 5,
    finish: 8.5,
    aromaIntensity: 8,
    citrus: 0.5,
    stoneFruit: 1,
    tropical: 0,
    redFruit: 7.5,
    blackFruit: 2,
    driedFruit: 1.5,
    floral: 5.5,
    herbal: 1.5,
    green: 0.5,
    spice: 3.5,
    oak: 3.5,
    nutty: 1,
    earthy: 4.5,
    aged: 3,
    comment:
      "赤いベリーとバラの華やかな香り。繊細なタンニンとシルキーな質感、複雑で長い余韻。",
  },
  {
    id: "seed-eval-dom-perignon",
    wineId: "seed-dom-perignon",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-03T09:00:00.000Z",
    sweetness: 1.5,
    acidity: 8,
    tannin: 0.5,
    body: 5,
    alcohol: 4.5,
    fruitiness: 5,
    minerality: 7.5,
    finish: 7.5,
    aromaIntensity: 7,
    citrus: 6.5,
    stoneFruit: 2.5,
    tropical: 1,
    redFruit: 1,
    blackFruit: 0,
    driedFruit: 0.5,
    floral: 3,
    herbal: 0.5,
    green: 0.5,
    spice: 1,
    oak: 2,
    nutty: 4.5,
    earthy: 1,
    aged: 4,
    comment:
      "シトラスとブリオッシュ香、緻密な泡とミネラル感。骨格のしっかりした辛口。",
  },
  {
    id: "seed-eval-opus-one",
    wineId: "seed-opus-one",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-04T09:00:00.000Z",
    sweetness: 1,
    acidity: 5.5,
    tannin: 6.5,
    body: 8,
    alcohol: 8,
    fruitiness: 8,
    minerality: 2.5,
    finish: 8,
    aromaIntensity: 8,
    citrus: 0.5,
    stoneFruit: 1,
    tropical: 0,
    redFruit: 3,
    blackFruit: 8,
    driedFruit: 2.5,
    floral: 2,
    herbal: 1.5,
    green: 0.5,
    spice: 3.5,
    oak: 6.5,
    nutty: 1.5,
    earthy: 1.5,
    aged: 2,
    comment:
      "凝縮感のある黒果実とカカオ、樽香。滑らかなタンニンとリッチな余韻。",
  },
  {
    id: "seed-eval-sassicaia",
    wineId: "seed-sassicaia",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-05T09:00:00.000Z",
    sweetness: 1,
    acidity: 6,
    tannin: 6,
    body: 7,
    alcohol: 6.5,
    fruitiness: 6.5,
    minerality: 3.5,
    finish: 7.5,
    aromaIntensity: 7,
    citrus: 0.5,
    stoneFruit: 1,
    tropical: 0,
    redFruit: 3.5,
    blackFruit: 6.5,
    driedFruit: 2,
    floral: 1.5,
    herbal: 3.5,
    green: 1.5,
    spice: 3,
    oak: 5,
    nutty: 1,
    earthy: 2.5,
    aged: 2,
    comment:
      "地中海ハーブを思わせる香り、カシスとタバコのニュアンス。骨格のしっかりしたミディアムボディ。",
  },
  {
    id: "seed-eval-penfolds-grange",
    wineId: "seed-penfolds-grange",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-06T09:00:00.000Z",
    sweetness: 1,
    acidity: 5,
    tannin: 6.5,
    body: 8.5,
    alcohol: 8.5,
    fruitiness: 7.5,
    minerality: 2,
    finish: 8,
    aromaIntensity: 8.5,
    citrus: 0,
    stoneFruit: 0.5,
    tropical: 0,
    redFruit: 2,
    blackFruit: 8,
    driedFruit: 3,
    floral: 1,
    herbal: 1,
    green: 0.5,
    spice: 6,
    oak: 7,
    nutty: 1.5,
    earthy: 2,
    aged: 2.5,
    comment:
      "黒胡椒とブラックベリーの濃密な香り、樽由来のトースト香。力強くフルボディ。",
  },
  {
    id: "seed-eval-chateau-yquem",
    wineId: "seed-chateau-yquem",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-07T09:00:00.000Z",
    sweetness: 9.5,
    acidity: 7,
    tannin: 0,
    body: 7.5,
    alcohol: 5.5,
    fruitiness: 6,
    minerality: 2,
    finish: 9,
    aromaIntensity: 8.5,
    citrus: 3,
    stoneFruit: 3.5,
    tropical: 2,
    redFruit: 0,
    blackFruit: 0,
    driedFruit: 7.5,
    floral: 2,
    herbal: 0.5,
    green: 0,
    spice: 1,
    oak: 3,
    nutty: 4,
    earthy: 0.5,
    aged: 6,
    comment:
      "蜂蜜とアプリコットのコンフィ、貴腐由来の複雑な甘香。高い酸が甘みを支え長い余韻へ。",
  },
  {
    id: "seed-eval-vega-sicilia-unico",
    wineId: "seed-vega-sicilia-unico",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-08T09:00:00.000Z",
    sweetness: 1,
    acidity: 5.5,
    tannin: 5.5,
    body: 7,
    alcohol: 6.5,
    fruitiness: 5,
    minerality: 2.5,
    finish: 8,
    aromaIntensity: 7.5,
    citrus: 0.5,
    stoneFruit: 1,
    tropical: 0,
    redFruit: 2.5,
    blackFruit: 4,
    driedFruit: 5,
    floral: 1,
    herbal: 1.5,
    green: 0.5,
    spice: 4,
    oak: 6.5,
    nutty: 3,
    earthy: 3.5,
    aged: 6.5,
    comment: "長期熟成由来の複雑な香り、ドライフルーツと樽、なめらかなタンニン。",
  },
  {
    id: "seed-eval-yellow-tail-shiraz",
    wineId: "seed-yellow-tail-shiraz",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-09T09:00:00.000Z",
    sweetness: 3,
    acidity: 4,
    tannin: 3.5,
    body: 5.5,
    alcohol: 5.5,
    fruitiness: 7.5,
    minerality: 1,
    finish: 4.5,
    aromaIntensity: 6,
    citrus: 0,
    stoneFruit: 0.5,
    tropical: 0.5,
    redFruit: 3,
    blackFruit: 6,
    driedFruit: 2,
    floral: 1,
    herbal: 0.5,
    green: 0.5,
    spice: 2,
    oak: 2,
    nutty: 0.5,
    earthy: 1,
    aged: 0.5,
    comment: "ジャムのような果実味と控えめなタンニン、飲みやすいカジュアルな一本。",
  },
  {
    id: "seed-eval-jacobs-creek-classic",
    wineId: "seed-jacobs-creek-classic",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-10T09:00:00.000Z",
    sweetness: 2,
    acidity: 4.5,
    tannin: 4,
    body: 5.5,
    alcohol: 5.5,
    fruitiness: 6.5,
    minerality: 1.5,
    finish: 5,
    aromaIntensity: 5.5,
    citrus: 0,
    stoneFruit: 0.5,
    tropical: 0,
    redFruit: 3.5,
    blackFruit: 5,
    driedFruit: 1.5,
    floral: 1,
    herbal: 1,
    green: 1,
    spice: 2.5,
    oak: 2.5,
    nutty: 0.5,
    earthy: 1,
    aged: 0.5,
    comment: "バランスの取れた果実味とほどよいタンニン、日常使いしやすい味わい。",
  },
  {
    id: "seed-eval-cono-sur-bicicleta-pinot",
    wineId: "seed-cono-sur-bicicleta-pinot",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-11T09:00:00.000Z",
    sweetness: 1.5,
    acidity: 6,
    tannin: 2.5,
    body: 4,
    alcohol: 4.5,
    fruitiness: 6,
    minerality: 2,
    finish: 4.5,
    aromaIntensity: 5.5,
    citrus: 0.5,
    stoneFruit: 1,
    tropical: 0,
    redFruit: 6.5,
    blackFruit: 1,
    driedFruit: 1,
    floral: 2,
    herbal: 1,
    green: 0.5,
    spice: 1,
    oak: 1,
    nutty: 0.5,
    earthy: 1.5,
    aged: 0.5,
    comment: "赤いベリーの軽やかな香りとフレッシュな酸、渋みは控えめで飲みやすい。",
  },
  {
    id: "seed-eval-carlo-rossi",
    wineId: "seed-carlo-rossi",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-12T09:00:00.000Z",
    sweetness: 3.5,
    acidity: 3.5,
    tannin: 2.5,
    body: 4,
    alcohol: 3.5,
    fruitiness: 6,
    minerality: 1,
    finish: 3.5,
    aromaIntensity: 4.5,
    citrus: 0,
    stoneFruit: 0.5,
    tropical: 0.5,
    redFruit: 4,
    blackFruit: 3,
    driedFruit: 1.5,
    floral: 0.5,
    herbal: 0.5,
    green: 0.5,
    spice: 1,
    oak: 0.5,
    nutty: 0.5,
    earthy: 0.5,
    aged: 0,
    comment: "軽やかで甘みのある果実味、渋みは少なくカジュアルに楽しめる。",
  },
  {
    id: "seed-eval-santa-helena-gran-reserva",
    wineId: "seed-santa-helena-gran-reserva",
    evaluatorId: "Claude",
    evaluatedAt: "2026-07-13T09:00:00.000Z",
    sweetness: 1.5,
    acidity: 4.5,
    tannin: 5,
    body: 6,
    alcohol: 5.5,
    fruitiness: 6,
    minerality: 2,
    finish: 5.5,
    aromaIntensity: 6,
    citrus: 0,
    stoneFruit: 0.5,
    tropical: 0,
    redFruit: 2.5,
    blackFruit: 6,
    driedFruit: 1.5,
    floral: 1,
    herbal: 2,
    green: 1,
    spice: 2,
    oak: 3,
    nutty: 0.5,
    earthy: 1.5,
    aged: 1,
    comment: "しっかりした黒果実の香りとほどよいタンニン、コスパの良いカベルネ。",
  },
]
